# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: opentelemetry-instrumentation-kafka-python
  version: "0.60b0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/opentelemetry_instrumentation_kafka_python-${{ version }}.tar.gz
  sha256: 03c9b8b58b5b40b5b453ea5b60db90b8a78a9212ce42a3ff4963ff35651de60b

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }},<4.0
    - kafka-python >=2.0,<3.0
    - opentelemetry-api >=1.5,<2.dev0
    - opentelemetry-instrumentation ==${{ version }}
    - opentelemetry-semantic-conventions ==${{ version }}

tests:
  - python:
      imports:
        - opentelemetry.instrumentation.kafka
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: OpenTelemetry Kafka-Python instrumentation
  homepage: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-kafka-python
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
